language: c

os:
  - osx
  - linux

notifications:
  email: false
  slack: true

env:
  global:
    - CODECOV_TOKEN="749f156c-d5c7-425f-a226-c52fac07344c"

branches:
  only:
    - master

install:
  - bash .travisInstall.bash

script:
  - bash .travisScript.bash
