language: c

os:
  - osx
  - linux

notifications:
  email: false
  slack: true

env:
  global:
    - CODECOV_TOKEN="749f156c-d5c7-425f-a226-c52fac07344c"

branches:
  only:
    - master

matrix:
  allow_failures:
    - os: linux
  fast_finish: true

install:
  - bash .travisInstall.bash

script:
  - bash .travisScript.bash

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
