- panel: controls
  - layer: 2
  - image: controlsOverlay
    - show: 0
    - clickable: 0
    - color: #00000000
    - layer: 1

  - panel: controlsMenu
    - show: 0
    - clickable: 0
    - pos: 0.1, 0.1
    - dim: 0.8, 0.8
    - layer: 2
    - image: controlsBackground
      - texture: ui/border1x1.tga

    - panel: controlsLeftSide
      - pos: 0.1, 0.1
      - dim: 0.40, 0.8

      - panel: controlsForward
        - pos: 0.05, 0.0
        - dim: 0.8, 0.20
        - text_block: controlsForwardText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Forward :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsForwardButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_forward
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

      - panel: controlsBackward
        - pos: 0.05, 0.22
        - dim: 0.8, 0.20
        - text_block: controlsBackwardText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Backward :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsBackwardButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_backward
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

      - panel: controlsLeft
        - pos: 0.05, 0.44
        - dim: 0.8, 0.20
        - text_block: controlsLeftText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Left :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsLeftButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_left
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

      - panel: controlsRight
        - pos: 0.05, 0.66
        - dim: 0.8, 0.20
        - text_block: controlsRightText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Right :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsRightButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_right
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

    - panel: controlsRightSide
      - pos: 0.50, 0.1
      - dim: 0.40, 0.8

      - panel: controlsInteract
        - pos: 0.05, 0.0
        - dim: 0.8, 0.20
        - text_block: controlsInteractText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Interact :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsInteractButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_interact
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

      - panel: controlsShoot
        - pos: 0.05, 0.22
        - dim: 0.8, 0.20
        - text_block: controlsShootText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Shoot :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsShootButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_shoot
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

      - panel: controlsCrouch
        - pos: 0.05, 0.44
        - dim: 0.8, 0.20
        - text_block: controlsCrouchText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Crouch :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsCrouchButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_crouch
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

      - panel: controlsJump
        - pos: 0.05, 0.66
        - dim: 0.8, 0.20
        - text_block: controlsJumpText
          - pos: 0.1, 0.1
          - dim: 0.6, 0.8
          - text: "Jump :"
          - text_font: foulfiend
          - text_color: #EAEAEA
          - text_size: 0.8
        - button: controlsJumpButton
          - pos: 0.75, 0.2
          - dim: 0.2, 0.6
          - onclick: controls_set_jump
          - texture: ui/border1x1.tga
          - text_font: foulfiend
          - text_size: 0.8

    - button: controlsReturnButton
      - pos: 0.2, 0.81
      - dim: 0.6, 0.1
      - text_size: 0.5
      - text: "Return"
      - text_font: foulfiend
      - text_color: #EAEAEA
      - texture: ui/border5x1.tga
      - onclick: controls_return

  - panel: controlsKeyChange
    - show: 0
    - clickable: 0
    - layer: 3
    - image: controlsKeyChangeOverlay
      - color: #00000000
    - panel: controlsKeyChangeBox
      - pos: 0.35, 0.45
      - dim: 0.3, 0.1
      - image: controlsKeyChangeBackground
        - texture: ui/border5x1.tga
      - text_block: controlsKeyChangeText
        - text: "Press/click DESIRED key"
        - text_font: foulfiend
        - text_color: #e3e3e3
        - text_size: 0.8
