- panel: hud
  - image: gamebg
    - color: #333333
  - panel: gviewpanel
    - gview: gameview
  - text_block: angle
    - pos: 0.1, 0.1
    - dim: 0.1, 0.1
    - text: "Angle: "
    - text_color: #FFFFFF
