- panel: hudOptions
  - layer: 2
  - image: hudOptionsOverlay
    - show: 0
    - clickable: 0
    - color: #26020699
    - layer: 1

  - panel: hudOptionsMenu
    - show: 0
    - clickable: 0
    - pos: 0.25, 0.25
    - dim: 0.5, 0.5
    - layer: 2
    - image: hudOptionsBackground
      - texture: ui/border1x1.tga

    - panel: hudSensitivity
      - pos: 0.1, 0.08
      - dim: 0.8, 0.2
      - text_block: hudSensitivityText
        - pos: 0.0, 0.05
        - dim: 1.0, 0.5
        - text_size: 0.8
        - text_font: foulfiend
        - text_color: #EAEAEA
        - text: "Sensitivity"
        - layer: 1
      - panel: hudSensitivityBlock
        - pos: 0.4, 0.5
        - dim: 0.2, 0.5
        - text_block: curHudSensitivity
          - pos: 0.2, 0.0
          - dim: 0.6, 1.0
          - text_size: 0.7
          - text_font: neckromancer
        - button: hudSensitivityLeft
          - pos: 0.0, 0.2
          - dim: 0.2, 0.6
          - texture: ui/arrow_left.tga
          - onclick: options_hud_sensitivity_down
        - button: hudSensitivityRight
          - pos: 0.8, 0.2
          - dim: 0.2, 0.6
          - texture: ui/arrow_right.tga
          - onclick: options_hud_sensitivity_up

    - panel: hudVolume
      - pos: 0.1, 0.28
      - dim: 0.8, 0.2
      - text_block: hudVolumeText
        - pos: 0.0, 0.05
        - dim: 1.0, 0.5
        - text_size: 0.8
        - text_font: foulfiend
        - text_color: #EAEAEA
        - text: "Volume"
      - panel: hudMusicVolumeBlock
        - pos: 0.0, 0.5
        - dim: 0.5, 0.5
        - text_block: hudMusicVolumeText
          - pos: 0.0, 0.0
          - dim: 0.5, 1.0
          - text_size: 0.6
          - text_font: neckromancer
          - text: "Music"
        - text_block: curHudMusicVolume
          - pos: 0.5, 0.0
          - dim: 0.25, 1.0
          - text_size: 0.6
          - text_font: neckromancer
        - button: hudMusicVolumeLeft
          - pos: 0.42, 0.2
          - dim: 0.08, 0.6
          - texture: ui/arrow_left.tga
          - onclick: options_hud_music_volume_down
        - button: hudMusicVolumeRight
          - pos: 0.75, 0.2
          - dim: 0.08, 0.6
          - texture: ui/arrow_right.tga
          - onclick: options_hud_music_volume_up
      - panel: hudSoundVolumeBlock
        - pos: 0.5, 0.5
        - dim: 0.5, 0.5
        - text_block: hudSoundVolumeText
          - pos: 0.0, 0.0
          - dim: 0.5, 1.0
          - text_size: 0.6
          - text_font: neckromancer
          - text: "Sound"
        - text_block: curHudSoundVolume
          - pos: 0.5, 0.0
          - dim: 0.25, 1.0
          - text_size: 0.6
          - text_font: neckromancer
        - button: hudSoundVolumeLeft
          - pos: 0.42, 0.2
          - dim: 0.08, 0.6
          - texture: ui/arrow_left.tga
          - onclick: options_hud_sound_volume_down
        - button: hudSoundVolumeRight
          - pos: 0.75, 0.2
          - dim: 0.08, 0.6
          - texture: ui/arrow_right.tga
          - onclick: options_hud_sound_volume_up

    - panel: hudFov
      - pos: 0.1, 0.48
      - dim: 0.8, 0.2
      - text_block: hudFovText
        - pos: 0.0, 0.05
        - dim: 1.0, 0.5
        - text_size: 0.8
        - text_font: foulfiend
        - text_color: #EAEAEA
        - text: "FOV"
      - panel: hudFovBlock
        - pos: 0.4, 0.5
        - dim: 0.2, 0.5
        - text_block: curHudFov
          - pos: 0.2, 0.0
          - dim: 0.6, 1.0
          - text_size: 0.7
          - text_font: neckromancer
        - button: hudFovLeft
          - pos: 0.0, 0.2
          - dim: 0.2, 0.6
          - texture: ui/arrow_left.tga
          - onclick: options_hud_fov_down
        - button: hudFovRight
          - pos: 0.8, 0.2
          - dim: 0.2, 0.6
          - texture: ui/arrow_right.tga
          - onclick: options_hud_fov_up

    - button: hudOptionsReturnButton
      - pos: 0.1, 0.73
      - dim: 0.8, 0.15
      - text_size: 0.5
      - text: "Return to menu"
      - text_font: foulfiend
      - text_color: #EAEAEA
      - onclick: hudOptions_return
      - texture: ui/border5x1.tga
