- panel: mainMenu
  - image: mainMenuBackground
    - color: #333333
  - image: logo
    - pos: 0.35, 0.02
    - dim: 0.29, 0.303
    - texture: splash/doom3.tga
  - panel: menu
    - pos: 0.15, 0.325
    - dim: 0.7, 0.65
    - image: menuBackground
      - texture: ui/border1x1_2.tga
    - button: mainMenuMapSelectButton
      - pos: 0.125, 0.1375
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Select Map"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_missions
    - button: mainMenuOptionsButton
      - pos: 0.125, 0.32917
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Options"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_options
    - button: mainMenuMapEditorButton
      - pos: 0.125, 0.52084
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Map Editor"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_mapeditor
    - button: mainMenuQuitButton
      - pos: 0.125, 0.7125
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Quit"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_quit
