- panel: mainmenu
  - image: mainmenubackground
    - color: #bb0a1e
  - image: logo
    - pos: 0.45, 0.025
    - dim: 0.1, 0.225
    - texture: splash/icon3.tga
    - draw_method: scaled
  - panel: menu
    - pos: 0.15, 0.275
    - dim: 0.7, 0.7
    - image: menubackground
      - texture: ui/border1x1.tga
    - button: mainmenuMapselectButton
      - pos: 0.125, 0.1375
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Select Map"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_missions
    - button: mainmenuOptionsButton
      - pos: 0.125, 0.4250
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Options"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_options
    - button: mainmenuQuitButton
      - pos: 0.125, 0.7125
      - dim: 0.75, 0.15
      - texture: ui/border5x1.tga
      - text: "Quit"
      - text_font: foulfiend
      - text_size: 0.63
      - text_color: #EAEAEA
      - text_draw_method: centered
      - onclick: mainmenu_quit
